sem_prof = 'Sem Professor'

aulas = {
		'1a' : {
			'Monday' : {
				'1' : ('Química', 'Adriana'),
				'2' : ('Português', 'Victor'),
				'3' : ('Biologia', 'Karla'),
				'4' : ('Estudo Orientado', 'Joanelice'),
				'5' : ('Língua Portuguesa', 'Victor'),
				'6' : ('Geografia', 'Edilson Carneiro'),
				'7' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'8' : ('Educação Física', 'David'),
				'9' : ('Esporte, Cultura e Arte na Prática', 'David')},
			'Tuesday' : {
				'1' : ('Lingua Inglesa', 'Ricleberson'),
				'2' : ('Matemática', 'Jussara Abreu'),
				'3' : ('Filosofia', sem_prof),
				'4' : ('Sociologia', 'Claudia'),
				'5' : ('Redação', 'Carla'),
				'6' : ('Eletivas', 'Vários professores'),
				'7' : ('Eletivas', 'Vários professores'),
				'8' : ('Projeto de Vida', 'Karla'),
				'9' : ('Projeto de Vida', 'Karla')},
			'Wednesday' : {
				'1' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'2' : ('Filosofia', sem_prof),
				'3' : ('História', 'Joanelice'),
				'4' : ('Estudo Orientado', 'Joanelice'),
				'5' : ('Operações Matemáticas', 'Jussara Abreu'),
				'6' : ('Educação Física', 'David'),
				'7' : ('Artes', 'Luciana'),
				'8' : ('Tutoria', 'Claudia'),
				'9' : ('Esporte, Cultura e Arte na Prática', 'David')},
			'Thursday' : {
				'1' : ('Língua Portuguesa', 'Victor'),
				'2' : ('Redação', 'Carla'),
				'3' : ('Física', 'Mário'),
				'4' : ('Sociologia', 'Claudia'),
				'5' : ('História', 'Joanelice'),
				'6' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'7' : ('Matemática', 'Jussara Abreu'),
				'8' : ('Geografia', 'Edilson Carneiro'),
				'9' : ('Física', 'Mário')},
			'Friday': {
				'1' : ('Língua Portuguesa', 'Victor'),
				'2' : ('Química', 'Adriana'),
				'3' : ('Artes', 'Luciana'),
				'4' : ('Estudo Orientado', 'Joanelice'),
				'5' : ('Biologia', 'Karla'),
				'6' : ('Operações Matemáticas', 'Jussara Abreu'),
				'7' : ('Matemática', 'Jussara Abreu'),
				'8' : ('Língua Inglesa', 'Ricleberson'),
				'9' : ('História, Cultura e Identidades Sergipanas', 'Joanelice')}},
		'1b' : {
			'Monday' : {
				'1' : ('História', 'Joanelice'),
				'2' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'3' : ('Língua Portuguesa', 'Victor'),
				'4' : ('Matemática', 'Jussara'),
				'5' : ('Geografia', 'Edilson Carneiro'),
				'6' : ('Química', 'Adriana'),
				'7' : ('Estudo Orientado', 'Adriana'),
				'8' : ('Biologia', 'Karla'),
				'9' : ('Geografia', 'Edilson')},
			'Tuesday' : {
				'1' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'2' : ('Língua Inglesa', 'Ricleberson'),
				'3' : ('Sociologia', 'Claudia'),
				'4' : ('Filosofia', sem_prof),
				'5' : ('Estudo Orientado', 'Adriana'),
				'6' : ('Eletivas', 'Vários Professores'),
				'7' : ('Eletivas', 'Vários Professores'),
				'8' : ('Língua Portuguesa', 'Victor'),
				'9' : ('Operações Matemáticas', 'Jussara Abreu')},
			'Wednesday' : {
				'1' : ('Educação Física', 'David'),
				'2' : ('Redação', 'Carla'),
				'3' : ('Filosofia', sem_prof),
				'4' : ('Educação Física', 'David'),
				'5' : ('Esporte, Arte e Cultura na Prática', 'David'),
				'6' : ('Projeto de Vida', 'Karla'),
				'7' : ('Projeto de Vida', 'Karla'),
				'8' : ('Tutoria', 'David'),
				'9' : ('Ecologia e Meio Ambiente', 'Kalideri')},
			'Thursday' : {
				'1' : ('Física', 'Mário'),
				'2' : ('Matemática', 'Jussara Abreu'),
				'3' : ('Língua Portuguesa', 'Victor'),
				'4' : ('Estudo Orientado', 'Adriana'),
				'5' : ('Química', 'Adriana'),
				'6' : ('Operações Matemáticas', 'Jussara Abreu'),
				'7' : ('Artes', 'Luciana'),
				'8' : ('História', 'Joanelice'),
				'9' : ('Língua Inglesa', 'Joanelice')},
			'Friday' : {
				'1' : ('Matemática', 'Jussara Abreu'),
				'2' : ('Física', 'Mário'),
				'3' : ('Redação', 'Carla'),
				'4' : ('Esporte, Cultura e Arte na Prática', 'David'),
				'5' : ('Artes', 'Luciana'),
				'6' : ('Língua Portuguesa', 'Victor'),
				'7' : ('Biologia', 'Karla'),
				'8' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'9' : ('Sociologia', 'Claudia')}},
		'1c' : {
			'Monday' : {
				'1' : ('Lingua Portuguesa', 'Victor'),
				'2' : ('Estudo Orientado', 'Edilson Carneiro'),
				'3' : ('Matemática', 'Jussara'),
				'4' : ('Lingua Portuguesa', 'Vitor'),
				'5' : ('História', 'Joanelice'),
				'6' : ('Biologia', 'Karla'),
				'7' : ('Educação Física', 'David'),
				'8' : ('Geografia', 'Edilson Carneiro'),
				'9' : ('Redação', 'Carla')},
			'Tuesday' : {
				'1' : ('Operações Matemáticas', 'Jussara Abreu'),
				'2' : ('Química', 'Adriana'),
				'3' : ('Artes', 'Luciana'),
				'4' : ('Matemática', 'Jussara Abreu'),
				'5' : ('Ecologia e Meio-Ambiente', 'Kalideri'),
				'6' : ('Eletiva', 'Vários'),
				'7' : ('Eletiva', 'Vários'),
				'8' : ('Sociologia', 'Claudia'),
				'9' : ('Esporte, Arte e Cultura na Prática', 'David')},
			'Wednesday' : {
				'1' : ('Filosofia', sem_prof),
				'2' : ('Projeto de Vida', 'Karla'),
				'3' : ('Projeto de Vida', 'Karla'),
				'4' : ('Operações Matemáticas', 'Jussara Abreu'),
				'5' : ('Filosofia', sem_prof),
				'6' : ('Física', 'Mário César'),
				'7' : ('Educação Física', 'David'),
				'8' : ('Tutoria', 'Edilson Carneiro'),
				'9' : ('Historia, Cultura e Identidades Sergipanas', 'Joanelice')},
			'Thursday' : {
				'1' : ('Química', 'Adriana'),
				'2' : ('Física', 'Mário'),
				'3' : ('Lingua Inglesa', 'Ricleberson'),
				'4' : ('Redação', 'Carla'),
				'5' : ('Sociologia', 'Claudia'),
				'6' : ('Artes', 'Luciana'),
				'7' : ('História', 'Joanelice'),
				'8' : ('Matemática', 'Jussara'),
				'9' : ('Estudo Orientado', 'Edilson Carneiro')},
			'Friday' : {
				'1' : ('Esporte, arte e cultura na Prática', 'David'),
				'2' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'3' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'4' : ('Biologia', 'Karla'),
				'5' : ('Portugês', 'Vitor'),
				'6' : ('Lingua Inglesa', 'Ricleberson'),
				'7' : ('Português', 'Victor'),
				'8' : ('Estudo Orientado', 'Edilson Carneiro'),
				'9' : ('Geografia', 'Edilson Carneiro')}},
		'2a': {
            'Monday' : {
                '1' : ('P.A.I. II', 'Joana'),
                '2' : ('Educação Física III', 'David'),
                '3' : ('Educação Física III', 'David'),
                '4' : ('Inglês Instrumental', 'Ricleberson'),
                '5' : ('Inglês Instrumental', 'Ricleberson'),
                '6' : ('Sociologia III', 'Claudia'),
                '7' : ('Contabilidade Aplicada', 'Cleide'),
                '8' : ('Química III', 'Adriana'),
                '9' : ('Atividade Integradora VIII', 'Kalderi')},
            'Tuesday' : {
                '1' : ('Filosofia III', sem_prof),
                '2' : ('Responsabilidade Social e Ambiental', 'Kalideri'),
                '3' : ('Língua Portuguesa III', 'Carla'),
                '4' : ('Protagonismo III', 'Luciana'),
                '5' : ('Matemática III', 'Jussara'),
                '6' : ('P.A.I. II', 'Joana'),
                '7' : ('Arte III', 'Luciana'),
                '8' : ('Tutoria III', 'Edilson'),
                '9' : ('Língua Portuguesa III', 'Carla')},
            'Wednesday' : {
                '1': ('Química III', 'Adriana'),
                '2': ('Língua Inglesa II', 'Ricleberson'),
                '3': ('Sociologia III', 'Claudia'),
                '4': ('Projeto de Vida III', 'Karla'),
                '5': ('Projeto de Vida III', 'Karla'),
                '6': ('Contanbilidade Aplicada', 'Cleide'),
                '7': ('Física III', 'Mário'),
                '8': ('Estudo Orientado III', 'Karla'),
                '9': ('Matemática III', 'Jussara')},
            'Thursday': {
                '1': ('Filosofia III', sem_prof),
                '2': ('Atividade Integradora VIII', 'Kalideri'),
                '3': ('Língua Portuguesa III', 'Carla'),
                '4': ('Protagonismo III', 'Luciana'),
                '5': ('Arte III', 'Luciana'),
                '6': ('Estatística Aplicada a Administração', 'Cleide'),
                '7': ('Responsabilidade Social e Ambiental', 'Kalideri'),
                '8': ('Estudo Orientado III', 'Victor'),
                '9': ('Contabilidade Aplicada', 'Cleide')},
            'Friday': {
                '1': ('Física III', 'Mário'),
                '2': ('', ''),
                '3': ('', ''),
                '4': ('', ''),
                '5': ('', ''),
                '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')}},
 '2b': {'Monday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')},
        'Tuesday': {'1': ('', ''),
                    '2': ('', ''),
                    '3': ('', ''),
                    '4': ('', ''),
                    '5': ('', ''),
                    '6': ('', ''),
                    '7': ('', ''),
                    '8': ('', ''),
                    '9': ('', '')},
        'Wednesday': {'1': ('', ''),
                      '2': ('', ''),
                      '3': ('', ''),
                      '4': ('', ''),
                      '5': ('', ''),
                      '6': ('', ''),
                      '7': ('', ''),
                      '8': ('', ''),
                      '9': ('', '')},
        'Thursday': {'1': ('', ''),
                     '2': ('', ''),
                     '3': ('', ''),
                     '4': ('', ''),
                     '5': ('', ''),
                     '6': ('', ''),
                     '7': ('', ''),
                     '8': ('', ''),
                     '9': ('', '')},
        'Friday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')}},
 '2c': {'Monday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')},
        'Tuesday': {'1': ('', ''),
                    '2': ('', ''),
                    '3': ('', ''),
                    '4': ('', ''),
                    '5': ('', ''),
                    '6': ('', ''),
                    '7': ('', ''),
                    '8': ('', ''),
                    '9': ('', '')},
        'Wednesday': {'1': ('', ''),
                      '2': ('', ''),
                      '3': ('', ''),
                      '4': ('', ''),
                      '5': ('', ''),
                      '6': ('', ''),
                      '7': ('', ''),
                      '8': ('', ''),
                      '9': ('', '')},
        'Thursday': {'1': ('', ''),
                     '2': ('', ''),
                     '3': ('', ''),
                     '4': ('', ''),
                     '5': ('', ''),
                     '6': ('', ''),
                     '7': ('', ''),
                     '8': ('', ''),
                     '9': ('', '')},
        'Friday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')}},
 '3a': {'Monday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')},
        'Tuesday': {'1': ('', ''),
                    '2': ('', ''),
                    '3': ('', ''),
                    '4': ('', ''),
                    '5': ('', ''),
                    '6': ('', ''),
                    '7': ('', ''),
                    '8': ('', ''),
                    '9': ('', '')},
        'Wednesday': {'1': ('', ''),
                      '2': ('', ''),
                      '3': ('', ''),
                      '4': ('', ''),
                      '5': ('', ''),
                      '6': ('', ''),
                      '7': ('', ''),
                      '8': ('', ''),
                      '9': ('', '')},
        'Thursday': {'1': ('', ''),
                     '2': ('', ''),
                     '3': ('', ''),
                     '4': ('', ''),
                     '5': ('', ''),
                     '6': ('', ''),
                     '7': ('', ''),
                     '8': ('', ''),
                     '9': ('', '')},
        'Friday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')}},
 '3b': {'Monday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')},
        'Tuesday': {'1': ('', ''),
                    '2': ('', ''),
                    '3': ('', ''),
                    '4': ('', ''),
                    '5': ('', ''),
                    '6': ('', ''),
                    '7': ('', ''),
                    '8': ('', ''),
                    '9': ('', '')},
        'Wednesday': {'1': ('', ''),
                      '2': ('', ''),
                      '3': ('', ''),
                      '4': ('', ''),
                      '5': ('', ''),
                      '6': ('', ''),
                      '7': ('', ''),
                      '8': ('', ''),
                      '9': ('', '')},
        'Thursday': {'1': ('', ''),
                     '2': ('', ''),
                     '3': ('', ''),
                     '4': ('', ''),
                     '5': ('', ''),
                     '6': ('', ''),
                     '7': ('', ''),
                     '8': ('', ''),
                     '9': ('', '')},
        'Friday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')}},
 '3c': {'Monday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')},
        'Tuesday': {'1': ('', ''),
                    '2': ('', ''),
                    '3': ('', ''),
                    '4': ('', ''),
                    '5': ('', ''),
                    '6': ('', ''),
                    '7': ('', ''),
                    '8': ('', ''),
                    '9': ('', '')},
        'Wednesday': {'1': ('', ''),
                      '2': ('', ''),
                      '3': ('', ''),
                      '4': ('', ''),
                      '5': ('', ''),
                      '6': ('', ''),
                      '7': ('', ''),
                      '8': ('', ''),
                      '9': ('', '')},
        'Thursday': {'1': ('', ''),
                     '2': ('', ''),
                     '3': ('', ''),
                     '4': ('', ''),
                     '5': ('', ''),
                     '6': ('', ''),
                     '7': ('', ''),
                     '8': ('', ''),
                     '9': ('', '')},
        'Friday': {'1': ('', ''),
                   '2': ('', ''),
                   '3': ('', ''),
                   '4': ('', ''),
                   '5': ('', ''),
                   '6': ('', ''),
                   '7': ('', ''),
                   '8': ('', ''),
                   '9': ('', '')}}}