sem_prof = 'Sem Professor'

aulas = {
		'1a' : {
			'Monday' : {
				'1' : ('Química', 'Adriana'),
				'2' : ('Português', 'Victor'),
				'3' : ('Biologia', 'Karla'),
				'4' : ('Estudo Orientado', 'Joanelice'),
				'5' : ('Língua Portuguesa', 'Victor'),
				'6' : ('Geografia', 'Edilson Carneiro'),
				'7' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'8' : ('Educação Física', 'David'),
				'9' : ('Esporte, Cultura e Arte na Prática', 'David')},
			'Tuesday' : {
				'1' : ('Lingua Inglesa', 'Ricleberson'),
				'2' : ('Matemática', 'Jussara Abreu'),
				'3' : ('Filosofia', sem_prof),
				'4' : ('Sociologia', 'Claudia'),
				'5' : ('Redação', 'Carla'),
				'6' : ('Eletivas', 'Vários professores'),
				'7' : ('Eletivas', 'Vários professores'),
				'8' : ('Projeto de Vida', 'Karla'),
				'9' : ('Projeto de Vida', 'Karla')},
			'Wednesday' : {
				'1' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'2' : ('Filosofia', sem_prof),
				'3' : ('História', 'Joanelice'),
				'4' : ('Estudo Orientado', 'Joanelice'),
				'5' : ('Operações Matemáticas', 'Jussara Abreu'),
				'6' : ('Educação Física', 'David'),
				'7' : ('Artes', 'Luciana'),
				'8' : ('Tutoria', 'Claudia'),
				'9' : ('Esporte, Cultura e Arte na Prática', 'David')},
			'Thursday' : {
				'1' : ('Língua Portuguesa', 'Victor'),
				'2' : ('Redação', 'Carla'),
				'3' : ('Física', 'Mário'),
				'4' : ('Sociologia', 'Claudia'),
				'5' : ('História', 'Joanelice'),
				'6' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'7' : ('Matemática', 'Jussara Abreu'),
				'8' : ('Geografia', 'Edilson Carneiro'),
				'9' : ('Física', 'Mário')},
			'Friday': {
				'1' : ('Língua Portuguesa', 'Victor'),
				'2' : ('Química', 'Adriana'),
				'3' : ('Artes', 'Luciana'),
				'4' : ('Estudo Orientado', 'Joanelice'),
				'5' : ('Biologia', 'Karla'),
				'6' : ('Operações Matemáticas', 'Jussara Abreu'),
				'7' : ('Matemática', 'Jussara Abreu'),
				'8' : ('Língua Inglesa', 'Ricleberson'),
				'9' : ('História, Cultura e Identidades Sergipanas', 'Joanelice')}},
		'1b' : {
			'Monday' : {
				'1' : ('História', 'Joanelice'),
				'2' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'3' : ('Língua Portuguesa', 'Victor'),
				'4' : ('Matemática', 'Jussara'),
				'5' : ('Geografia', 'Edilson Carneiro'),
				'6' : ('Química', 'Adriana'),
				'7' : ('Estudo Orientado', 'Adriana'),
				'8' : ('Biologia', 'Karla'),
				'9' : ('Geografia', 'Edilson')},
			'Tuesday' : {
				'1' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'2' : ('Língua Inglesa', 'Ricleberson'),
				'3' : ('Sociologia', 'Claudia'),
				'4' : ('Filosofia', sem_prof),
				'5' : ('Estudo Orientado', 'Adriana'),
				'6' : ('Eletivas', 'Vários Professores'),
				'7' : ('Eletivas', 'Vários Professores'),
				'8' : ('Língua Portuguesa', 'Victor'),
				'9' : ('Operações Matemáticas', 'Jussara Abreu')},
			'Wednesday' : {
				'1' : ('Educação Física', 'David'),
				'2' : ('Redação', 'Carla'),
				'3' : ('Filosofia', sem_prof),
				'4' : ('Educação Física', 'David'),
				'5' : ('Esporte, Arte e Cultura na Prática', 'David'),
				'6' : ('Projeto de Vida', 'Karla'),
				'7' : ('Projeto de Vida', 'Karla'),
				'8' : ('Tutoria', 'David'),
				'9' : ('Ecologia e Meio Ambiente', 'Kalideri')},
			'Thursday' : {
				'1' : ('Física', 'Mário'),
				'2' : ('Matemática', 'Jussara Abreu'),
				'3' : ('Língua Portuguesa', 'Victor'),
				'4' : ('Estudo Orientado', 'Adriana'),
				'5' : ('Química', 'Adriana'),
				'6' : ('Operações Matemáticas', 'Jussara Abreu'),
				'7' : ('Artes', 'Luciana'),
				'8' : ('História', 'Joanelice'),
				'9' : ('Língua Inglesa', 'Joanelice')},
			'Friday' : {
				'1' : ('Matemática', 'Jussara Abreu'),
				'2' : ('Física', 'Mário'),
				'3' : ('Redação', 'Carla'),
				'4' : ('Esporte, Cultura e Arte na Prática', 'David'),
				'5' : ('Artes', 'Luciana'),
				'6' : ('Língua Portuguesa', 'Victor'),
				'7' : ('Biologia', 'Karla'),
				'8' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'9' : ('Sociologia', 'Claudia')}},

		'1c' : {
			'Monday' : {
				'1' : ('Lingua Portuguesa', 'Victor'),
				'2' : ('Estudo Orientado', 'Edilson Carneiro'),
				'3' : ('Matemática', 'Jussara'),
				'4' : ('Lingua Portuguesa', 'Vitor'),
				'5' : ('História', 'Joanelice'),
				'6' : ('Biologia', 'Karla'),
				'7' : ('Educação Física', 'David'),
				'8' : ('Geografia', 'Edilson Carneiro'),
				'9' : ('Redação', 'Carla')},
			'Tuesday' : {
				'1' : ('Operações Matemáticas', 'Jussara Abreu'),
				'2' : ('Química', 'Adriana'),
				'3' : ('Artes', 'Luciana'),
				'4' : ('Matemática', 'Jussara Abreu'),
				'5' : ('Ecologia e Meio-Ambiente', 'Kalideri'),
				'6' : ('Eletiva', 'Vários'),
				'7' : ('Eletiva', 'Vários'),
				'8' : ('Sociologia', 'Claudia'),
				'9' : ('Esporte, Arte e Cultura na Prática', 'David')},
			'Wednesday' : {
				'1' : ('Filosofia', sem_prof),
				'2' : ('Projeto de Vida', 'Karla'),
				'3' : ('Projeto de Vida', 'Karla'),
				'4' : ('Operações Matemáticas', 'Jussara Abreu'),
				'5' : ('Filosofia', sem_prof),
				'6' : ('Física', 'Mário César'),
				'7' : ('Educação Física', 'David'),
				'8' : ('Tutoria', 'Edilson Carneiro'),
				'9' : ('Historia, Cultura e Identidades Sergipanas', 'Joanelice')},
			'Thursday' : {
				'1' : ('Química', 'Adriana'),
				'2' : ('Física', 'Mário'),
				'3' : ('Lingua Inglesa', 'Ricleberson'),
				'4' : ('Redação', 'Carla'),
				'5' : ('Sociologia', 'Claudia'),
				'6' : ('Artes', 'Luciana'),
				'7' : ('História', 'Joanelice'),
				'8' : ('Matemática', 'Jussara'),
				'9' : ('Estudo Orientado', 'Edilson Carneiro')},
			'Friday' : {
				'1' : ('Esporte, arte e cultura na Prática', 'David'),
				'2' : ('História, Cultura e Identidades Sergipanas', 'Joanelice'),
				'3' : ('Ecologia e Meio Ambiente', 'Kalideri'),
				'4' : ('Biologia', 'Karla'),
				'5' : ('Portugês', 'Vitor'),
				'6' : ('Lingua Inglesa', 'Ricleberson'),
				'7' : ('Português', 'Victor'),
				'8' : ('Estudo Orientado', 'Edilson Carneiro'),
				'9' : ('Geografia', 'Edilson Carneiro')}},}